# Generated by Django 5.0 on 2023-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_europa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disney',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='europa',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
