# Generated by Django 5.0 on 2023-12-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_disney_descripcion_alter_europa_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disney',
            options={'verbose_name': 'Paquetes de Disney'},
        ),
        migrations.AlterModelOptions(
            name='europa',
            options={'verbose_name': 'Paquetes de Europa'},
        ),
        migrations.AlterField(
            model_name='disney',
            name='imagen',
            field=models.ImageField(upload_to='disneys'),
        ),
        migrations.AlterField(
            model_name='europa',
            name='imagen',
            field=models.ImageField(upload_to='europas'),
        ),
    ]
